# fly.toml app configuration file generated for microposts-little-snowflake-3953 on 2025-06-23T14:52:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'microposts-little-snowflake-3953'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://microposts-little-snowflake-3953.fly.dev'
  APP_NAME = 'Laravel'
  APP_DEBUG = false
  
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION="pgsql"
  DB_HOST="aws-0-ap-northeast-1.pooler.supabase.com"
  DB_PORT=5432
  DB_DATABASE="postgres"
  DB_USERNAME="postgres.nxxrlkhwulsfqipvuwih"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
